### ISSUE TITLE
Support for Java 11

### ISSUE THREAD

**Issue by mrjavascript** [kpalang/mirth-sample-plugin#1]
Does this project offer support for JDK 11?  Mirth 3.12.0 release is using 11.

**Comment by kpalang** [comment]
As far as I know, it does.
In the [accompanying development guide](https://github.com/kpalang/mirth-plugin-guide) I've included a [Docker Compose](https://github.com/kpalang/mirth-plugin-guide/blob/master/docker-compose.yaml) with Connect 3.12 in it that I use to test the stuff I write about.
