### ISSUE TITLE
Maven dependencies not found

### ISSUE THREAD

**Issue by chrmey** [kpalang/mirth-sample-plugin#2]
Hi there, i'm absolutely new to mirth plugin development and since there is next to no documentation on this, i wanted to use your guide and example. Sadly, the maven dependencies cannot be found. Do you have any idea on this?

Thanks in advance!

**Comment by jonbartels** [comment]
You need to show the errors you got when running Maven.

Remember to use code formatting so we can read the errors https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by kpalang** [comment]
Apologies, you've managed to hit the exact time of technical difficulties :)
The maven server is indeed currently offline.

I am working on getting it back, and will definitely inform about it here.
Meanwhile you are welcome to hang out at the [Mirth Slack](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel) workspace and see me shouting at various things in #plugin-development channel.

**Comment by kpalang** [comment]
Hi, @chrmey!
I'm letting you know that https://maven.kaurpalang.com repository is once again up and functional. Currently, it is missing the `mirth-plugin-maven-plugin` artifact, but for the time being you can import this manually from [GitHub](https://github.com/kpalang/mirth-plugin-maven-plugin)

If you have any questions, don't hesitate to join the [Mirth Slack](https://mirthconnect.herokuapp.com/) and ask around in either `#general` or `#plugin-development`.
